ALTER TABLE user_match ADD COLUMN team INTEGER NOT NULL DEFAULT 0;
ALTER TABLE matches ALTER COLUMN score1 DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN score2 DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN score1 DROP DEFAULT;
ALTER TABLE matches ALTER COLUMN score2 DROP DEFAULT;