run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - deadcode
    - unused
    - structcheck
    - varcheck
    - revive
    - gofmt
    - goimports
    - misspell

  disable:
    - staticcheck
    - typecheck
    - nilness
    - unusedresult
    - prealloc
    - funlen
    - gocyclo
    - interfacer
    - lll
    - gocognit