name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'

      - name: Set up Docker (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Launch Postgres (CI compose)
        run: make docker-up-ci

      - name: Debug status (optionnel mais super utile si ça recasse)
        run: |
          docker ps -a
          docker logs pg_test || true

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            # Ici on teste depuis l'hôte vers le port publié 5433,
            # pas besoin de docker exec (et ça évite l'erreur "container is not running").
            if pg_isready -h 127.0.0.1 -p 5433 -U test -d test; then
              echo "Postgres is ready!"
              exit 0
            fi

            echo "Postgres not ready yet, retrying..."
            sleep 1
          done

          echo "Postgres never became ready, showing logs:"
          docker logs pg_test || true
          exit 1

      - name: Run tests
        run: make test-ci