name: Run Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BackEnd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up Docker (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Run make test (with Docker)
        run: make test