name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'

      - name: Set up Docker (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Launch Docker
        run: make docker-up

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            if docker exec pg_test pg_isready -U test -d test -h localhost -p 5432; then
              echo "Postgres is ready!"
              break
            fi
            echo "Postgres not ready yet, retrying..."
            sleep 1
          done

      - name: Run make test (with Docker)
        run: make test