name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'

      - name: Set up Docker (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Launch Docker
        run: make docker-up

      - name: Run make test (with Docker)
        run: make test